/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import vista.*;
/**
 *
 * @author carva
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RealizarVentaBoton = new javax.swing.JButton();
        VerInventarioBoton = new javax.swing.JButton();
        IngresarStockBoton = new javax.swing.JButton();
        VerClientesBoton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RealizarVentaBoton.setText("Realizar Venta");
        RealizarVentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarVentaBotonActionPerformed(evt);
            }
        });

        VerInventarioBoton.setText("Ver Inventario");
        VerInventarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerInventarioBotonActionPerformed(evt);
            }
        });

        IngresarStockBoton.setText("Ingresar Stock");
        IngresarStockBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarStockBotonActionPerformed(evt);
            }
        });

        VerClientesBoton.setText("Ver Clientes");
        VerClientesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerClientesBotonActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IngresarStockBoton)
                    .addComponent(RealizarVentaBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VerInventarioBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VerClientesBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RealizarVentaBoton)
                    .addComponent(VerInventarioBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarStockBoton)
                    .addComponent(VerClientesBoton))
                .addGap(55, 55, 55)
                .addComponent(jButton5)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RealizarVentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarVentaBotonActionPerformed
        // TODO add your handling code here:
        IniciarVenta nuevaVenta = new IniciarVenta();
        nuevaVenta.setVisible(true);
    }//GEN-LAST:event_RealizarVentaBotonActionPerformed

    private void IngresarStockBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarStockBotonActionPerformed
        // TODO add your handling code here:
        IngresarStock ingresarStock = new IngresarStock();
        ingresarStock.setVisible(true);
    }//GEN-LAST:event_IngresarStockBotonActionPerformed

    private void VerInventarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerInventarioBotonActionPerformed
        // TODO add your handling code here:
        VerInventario inventario = new VerInventario();
        inventario.setVisible(true);
        System.out.print("\nID Producto: ");
        int id = leerEntero();

        System.out.print("Cantidad a ingresar: ");
        int cantidad = leerEntero();

        boolean ok = controlInv.ingresarStock(id, cantidad);

        if (ok)
            System.out.println("Stock actualizado correctamente.");
        else
            System.out.println("ERROR: No se pudo ingresar el stock.");
    }//GEN-LAST:event_VerInventarioBotonActionPerformed

    private void VerClientesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerClientesBotonActionPerformed
        // TODO add your handling code here:
        VerCliente listaClientes = new VerCliente();
        listaClientes.setVisible(true);
    }//GEN-LAST:event_VerClientesBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarStockBoton;
    private javax.swing.JButton RealizarVentaBoton;
    private javax.swing.JButton VerClientesBoton;
    private javax.swing.JButton VerInventarioBoton;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
