package vista;
import controlador.ControladorInventario;
import controlador.ControladorSistemaVentas;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author carva
 */
public class IniciarVenta extends javax.swing.JFrame {

    // 1. Atributo para almacenar el controlador
    private final ControladorSistemaVentas controlVentas;

    // 2. Constructor
    public IniciarVenta(ControladorSistemaVentas controlVentas) {
        this.controlVentas = controlVentas; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RutClienteTextField = new javax.swing.JTextField();
        IngresarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIAR VENTA");

        jLabel2.setText("Rut Cliente:");

        RutClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutClienteTextFieldActionPerformed(evt);
            }
        });

        IngresarBoton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusColor"));
        IngresarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IngresarBoton.setText("INGRESAR");
        IngresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(IngresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RutClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RutClienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(IngresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBotonActionPerformed
        String rutCliente = RutClienteTextField.getText().trim();
        
        // 1. Validación de interfaz: si el campo está vacío
        if (rutCliente.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese el RUT.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. 🟢 CRÍTICO: Buscar el cliente delegando al controlador
        Distribuidor cliente = controlVentas.buscarCliente(rutCliente);
        
        // 3. Evaluar el resultado de la búsqueda
        if (cliente != null) {
            
            // Si el cliente existe:
            // 4. Flujo de Negocio: Iniciar Pedido (Controlador)
            Pedido nuevoPedido = controlVentas.iniciarPedido(cliente);
            
            // 5. Abrir la siguiente ventana (GenerarPedido) e inyectar el estado/lógica
            GenerarPedido pedidoGUI = new GenerarPedido(controlVentas, nuevoPedido);
            pedidoGUI.setLocationRelativeTo(this);
            pedidoGUI.setVisible(true);
            
            this.dispose(); // Cierra la ventana actual
            
        } else {
            // Si el cliente NO existe:
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente no encontrado.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IngresarBotonActionPerformed

    
    
    private void RutClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutClienteTextFieldActionPerformed
        // TODO add your handling code here:
        String rutCliente = RutClienteTextField.getText().trim();
        
        // 2. Validación: Que no esté vacío
        if (rutCliente.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, ingrese un RUT.");
            return; // Detenemos la ejecución si está vacío
        }
    }//GEN-LAST:event_RutClienteTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarBoton;
    private javax.swing.JTextField RutClienteTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
