package vista;
import controlador.ControladorSistemaVentas;
import modelo.Distribuidor;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class VerCliente extends javax.swing.JFrame {

    private final ControladorSistemaVentas controlVentas;
    private TableRowSorter<DefaultTableModel> sorter;
    public VerCliente(ControladorSistemaVentas controlVentas) {
        this.controlVentas = controlVentas;
        initComponents();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClienteTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BuscarPorRutjTextField = new javax.swing.JTextField();
        BuscarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ClienteTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Direccion", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(ClienteTabla);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTADO DE CLIENTES");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("INGRESE RUT:");

        BuscarPorRutjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorRutjTextFieldActionPerformed(evt);
            }
        });

        BuscarBoton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusColor"));
        BuscarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BuscarBoton.setText("BUSCAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(BuscarPorRutjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(BuscarBoton)
                .addGap(51, 51, 51))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarPorRutjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(BuscarBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarTabla() {
        // 1. Definir las columnas
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"RUT", "Nombre", "Direccion", "Tipo"}, 0
        );
        ClienteTabla.setModel(model);

        // 2. Obtener datos (Asumiendo que el método existe en el controlador)
        List<Distribuidor> lista = controlVentas.obtenerClientes(); 
        
        // 3. Llenar filas
        for (Distribuidor d : lista) {
            model.addRow(new Object[]{
                d.getRut(),
                d.getNombre(),
                d.getDireccion(),
                d.getTipo() 
            });
        }
        
        // 4. Inicializar el sorter para habilitar el filtrado
        sorter = new TableRowSorter<>(model);
        ClienteTabla.setRowSorter(sorter);
    }
    
    private void BuscarPorRutjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorRutjTextFieldActionPerformed
        filtrarTablaPorRUT();
    }//GEN-LAST:event_BuscarPorRutjTextFieldActionPerformed

    private void BuscarBotonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        filtrarTablaPorRUT(); 
    }
    
    private void filtrarTablaPorRUT() {
        String texto = BuscarPorRutjTextField.getText().trim();
        
        if (texto.length() == 0) {
            sorter.setRowFilter(null); // Mostrar todos
        } else {
            try {
                // Filtramos por la columna 0 (RUT). 
                // Buscamos coincidencias que *contengan* el texto ingresado.
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto, 0)); 
            } catch (java.util.regex.PatternSyntaxException e) {
                sorter.setRowFilter(null); 
                JOptionPane.showMessageDialog(this, "RUT ingresado inválido.", "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarBoton;
    private javax.swing.JTextField BuscarPorRutjTextField;
    private javax.swing.JTable ClienteTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
