package modelo;
public enum TipoMarca {
    KENT_SILVER_NEO,
    LUCKY_STRIKE_RED,
    LUCKY_STRIKE_BLUE,
    PALL_MALL_AZUL,
    CAMEL_FILTERS,
    GOLD_LEAF_ORIGINAL,
    DUNHILL_INTERNATIONAL,
    FILTROS_OCB_SLIM
}